// Maps slug from Supabase `services` table's `name` column

export const serviceDisplayNames: Record<string, string> = {
    acm: 'AWS Certificate Manager (ACM)',
    alb: 'Application Load Balancer (ALB)',
    'amazon-q': 'Amazon Q',
    'amazon-q-developer': 'Amazon Q Developer',
    ams: 'AWS Managed Services (AMS)',
    'api-gateway': 'Amazon API Gateway',
    'application-composer': 'AWS Application Composer',
    artifact: 'AWS Artifact',
    athena: 'Amazon Athena',
    'audit-manager': 'AWS Audit Manager',
    'augmented-ai': 'Amazon Augmented AI (A2I)',
    aurora: 'Amazon Aurora',
    'auto-scaling': 'Amazon EC2 Auto Scaling',
    'aws-budgets': 'AWS Budgets',
    'aws-cli': 'AWS Command Line Interface (CLI)',
    'aws-iq': 'AWS IQ',
    backup: 'AWS Backup',
    bedrock: 'Amazon Bedrock',
    'bedrock-agents': 'Amazon Bedrock Agents',
    'bedrock-guardrails': 'Amazon Bedrock Guardrails',
    cdk: 'AWS Cloud Development Kit (CDK)',
    'cloud-map': 'AWS Cloud Map',
    cloud9: 'AWS Cloud9',
    cloudformation: 'AWS CloudFormation',
    cloudfront: 'Amazon CloudFront',
    cloudhsm: 'AWS CloudHSM',
    cloudshell: 'AWS CloudShell',
    cloudtrail: 'AWS CloudTrail',
    cloudwatch: 'Amazon CloudWatch',
    codebuild: 'AWS CodeBuild',
    codecatalyst: 'Amazon CodeCatalyst',
    codecommit: 'AWS CodeCommit',
    codedeploy: 'AWS CodeDeploy',
    codepipeline: 'AWS CodePipeline',
    cognito: 'Amazon Cognito',
    comprehend: 'Amazon Comprehend',
    'comprehend-medical': 'Amazon Comprehend Medical',
    'compute-optimizer': 'AWS Compute Optimizer',
    config: 'AWS Config',
    'control-tower': 'AWS Control Tower',
    'cost-explorer': 'AWS Cost Explorer',
    'data-catalog': 'AWS Glue Data Catalog',
    'data-quality': 'AWS Glue Data Quality',
    databrew: 'AWS Glue DataBrew',
    datasync: 'AWS DataSync',
    dax: 'Amazon DynamoDB Accelerator (DAX)',
    deepracer: 'AWS DeepRacer',
    'direct-connect': 'AWS Direct Connect',
    'directory-service': 'AWS Directory Service',
    dms: 'AWS Database Migration Service (DMS)',
    dynamodb: 'Amazon DynamoDB',
    ebs: 'Amazon Elastic Block Store (EBS)',
    ec2: 'Amazon Elastic Compute Cloud (EC2)',
    ecr: 'Amazon Elastic Container Registry (ECR)',
    ecs: 'Amazon Elastic Container Service (ECS)',
    efs: 'Amazon Elastic File System (EFS)',
    'elastic-beanstalk': 'AWS Elastic Beanstalk',
    elasticache: 'Amazon ElastiCache',
    elb: 'Elastic Load Balancing (ELB)',
    emr: 'Amazon EMR',
    eventbridge: 'Amazon EventBridge',
    fargate: 'AWS Fargate',
    firehose: 'Amazon Data Firehose',
    'firewall-manager': 'AWS Firewall Manager',
    flink: 'Apache Flink',
    forecast: 'Amazon Forecast',
    'fraud-detector': 'Amazon Fraud Detector',
    fsx: 'Amazon FSx',
    glacier: 'Amazon S3 Glacier',
    glue: 'AWS Glue',
    'glue-crawler': 'AWS Glue Crawler',
    guardduty: 'Amazon GuardDuty',
    iam: 'AWS Identity and Access Management (IAM)',
    'iam-access-analyzer': 'IAM Access Analyzer',
    'iam-identity-center': 'AWS IAM Identity Center',
    inferentia: 'AWS Inferentia',
    inspector: 'Amazon Inspector',
    'iot-greengrass': 'AWS IoT Greengrass',
    kafka: 'Apache Kafka',
    kendra: 'Amazon Kendra',
    kinesis: 'Amazon Kinesis',
    'kinesis-data-streams': 'Amazon Kinesis Data Streams',
    kms: 'AWS Key Management Service (KMS)',
    'lake-formation': 'AWS Lake Formation',
    lambda: 'AWS Lambda',
    lex: 'Amazon Lex',
    'license-manager': 'AWS License Manager',
    'local-zones': 'AWS Local Zones',
    macie: 'Amazon Macie',
    'managed-service-for-apache-flink':
        'Amazon Managed Service for Apache Flink',
    'migration-hub': 'AWS Migration Hub',
    msk: 'Amazon Managed Streaming for Apache Kafka (MSK)',
    mwaa: 'Amazon Managed Workflows for Apache Airflow (MWAA)',
    nacl: 'Network Access Control List (NACL)',
    'nat-gateway': 'NAT Gateway',
    neptune: 'Amazon Neptune',
    'network-firewall': 'AWS Network Firewall',
    nlb: 'Network Load Balancer (NLB)',
    opensearch: 'Amazon OpenSearch Service',
    organizations: 'AWS Organizations',
    outposts: 'AWS Outposts',
    'parameter-store': 'Systems Manager Parameter Store',
    partyrock: 'PartyRock',
    personalize: 'Amazon Personalize',
    polly: 'Amazon Polly',
    privatelink: 'AWS PrivateLink',
    proton: 'AWS Proton',
    quicksight: 'Amazon QuickSight',
    ram: 'AWS Resource Access Manager (RAM)',
    rds: 'Amazon Relational Database Service (RDS)',
    'rds-proxy': 'Amazon RDS Proxy',
    redshift: 'Amazon Redshift',
    rekognition: 'Amazon Rekognition',
    repost: 'AWS re:Post',
    route53: 'Amazon Route 53',
    s3: 'Amazon Simple Storage Service (S3)',
    's3-object-lock': 'Amazon S3 Object Lock',
    sagemaker: 'Amazon SageMaker',
    'sagemaker-batch-transform': 'SageMaker Batch Transform',
    'sagemaker-built-in-algorithms': 'SageMaker Built-in Algorithms',
    'sagemaker-canvas': 'SageMaker Canvas',
    'sagemaker-clarify': 'SageMaker Clarify',
    'sagemaker-data-wrangler': 'SageMaker Data Wrangler',
    'sagemaker-debugger': 'SageMaker Debugger',
    'sagemaker-deepar': 'SageMaker DeepAR',
    'sagemaker-elastic-inference': 'SageMaker Elastic Inference',
    'sagemaker-endpoints': 'SageMaker Endpoints',
    'sagemaker-feature-store': 'SageMaker Feature Store',
    'sagemaker-ground-truth': 'SageMaker Ground Truth',
    'sagemaker-hyperparameter-tuning': 'SageMaker Hyperparameter Tuning',
    'sagemaker-jumpstart': 'SageMaker JumpStart',
    'sagemaker-model-cards': 'SageMaker Model Cards',
    'sagemaker-model-monitor': 'SageMaker Model Monitor',
    'sagemaker-model-registry': 'SageMaker Model Registry',
    'sagemaker-neo': 'SageMaker Neo',
    'sagemaker-pipelines': 'SageMaker Pipelines',
    'sagemaker-processing': 'SageMaker Processing',
    'sagemaker-training': 'SageMaker Training',
    sam: 'AWS Serverless Application Model (SAM)',
    'savings-plans': 'Savings Plans',
    scp: 'Service Control Policies (SCP)',
    'secrets-manager': 'AWS Secrets Manager',
    'security-groups': 'Security Groups',
    'security-hub': 'AWS Security Hub',
    'service-catalog': 'AWS Service Catalog',
    'service-quotas': 'Service Quotas',
    shield: 'AWS Shield',
    snowball: 'AWS Snowball',
    'snowball-edge': 'AWS Snowball Edge',
    snowcone: 'AWS Snowcone',
    sns: 'Amazon Simple Notification Service (SNS)',
    spark: 'Apache Spark',
    'spot-instances': 'Amazon EC2 Spot Instances',
    sqs: 'Amazon Simple Queue Service (SQS)',
    sso: 'AWS Single Sign-On (SSO)',
    'stable-diffusion': 'Stable Diffusion',
    'step-functions': 'AWS Step Functions',
    'storage-gateway': 'AWS Storage Gateway',
    sts: 'AWS Security Token Service (STS)',
    'systems-manager': 'AWS Systems Manager',
    textract: 'Amazon Textract',
    timestream: 'Amazon Timestream',
    titan: 'Amazon Titan',
    trainium: 'AWS Trainium',
    'transit-gateway': 'AWS Transit Gateway',
    translate: 'Amazon Translate',
    'trusted-advisor': 'AWS Trusted Advisor',
    vpc: 'Amazon Virtual Private Cloud (VPC)',
    'vpc-endpoint': 'VPC Endpoints',
    'vpc-peering': 'VPC Peering',
    vpn: 'AWS VPN',
    waf: 'AWS WAF',
    wavelength: 'AWS Wavelength',
    'well-architected-tool': 'AWS Well-Architected Tool',
    xgboost: 'XGBoost',
    xray: 'AWS X-Ray',
}

export function getServiceDisplayName(slug: string): string {
    const displayName = serviceDisplayNames[slug]

    if (displayName) {
        return displayName
    }

    return slug
}
